name: 'Label Manager for Issues by Column'
description: 'Adds/removes/sets lables for issues depending on what column they are in in a project.'
inputs:
  columns_actions_labels:
    description: 'An array of objects each containing a column reference and an array of objects each containing an action(set, add, remove) and an array of labels'
    required: true
  token:
    description: 'Token for api usage provided by github'
    required: true
    default: ''
runs:
  using: 'node20'
  main: 'index.js'
